# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux-qt6-next.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/yaml-lint.yml
      - /gitlab-templates/qml-lint.yml

suse_tumbleweed_qt610_reduced_featureset:
  extends: suse_tumbleweed_qt610
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - python3 -u ci-utilities/run-ci-build.py --project $CI_PROJECT_NAME --branch $CI_COMMIT_REF_NAME --platform Linux --extra-cmake-args="-DWITH_X11=OFF -DCMAKE_DISABLE_FIND_PACKAGE_KSysGuard=ON -DCMAKE_DISABLE_FIND_PACKAGE_QALCULATE=ON" --skip-publishing --only-build
