# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/attica': 'Frameworks/6.24'
    'frameworks/baloo': 'Frameworks/6.24'
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kauth': 'Frameworks/6.24'
    'frameworks/kbookmarks': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/kcodecs': 'Frameworks/6.24'
    'frameworks/kcompletion': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kdeclarative': 'Frameworks/6.24'
    'frameworks/kfilemetadata': 'Frameworks/6.24'
    'frameworks/kglobalaccel': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'frameworks/kitemviews': 'Frameworks/6.24'
    'frameworks/kjobwidgets': 'Frameworks/6.24'
    'frameworks/knewstuff': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/knotifyconfig': 'Frameworks/6.24'
    'frameworks/kpackage': 'Frameworks/6.24'
    'frameworks/kparts': 'Frameworks/6.24'
    'frameworks/krunner': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/ktexteditor': 'Frameworks/6.24'
    'frameworks/ktextwidgets': 'Frameworks/6.24'
    'frameworks/kwallet': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/solid': 'Frameworks/6.24'
    'frameworks/sonnet': 'Frameworks/6.24'
    'frameworks/kholidays': 'Frameworks/6.24'
    'frameworks/kquickcharts': 'Frameworks/6.24'
    'frameworks/kded': 'Frameworks/6.24'
    'frameworks/prison': 'Frameworks/6.24'
    'frameworks/kstatusnotifieritem': 'Frameworks/6.24'
    'frameworks/kuserfeedback': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'
    'plasma/kwayland': '@same'
    'plasma/libplasma': '@same'
    'plasma/layer-shell-qt': '@same'
    'plasma/kglobalacceld': '@same'
    'plasma/kscreenlocker': '@same'
    'plasma/libkscreen': '@same'
    'plasma/libksysguard': '@same'
    'plasma/plasma-nano': '@same'
    'plasma/plasma-activities': '@same'
    'plasma/plasma-activities-stats': '@same'
    'plasma/knighttime': '@same'
    'plasma/kwin': '@same'
    'libraries/plasma-wayland-protocols': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'
    'graphics/libkexiv2': 'release/25.12'
    'third-party/appstream': '@latest'
    'third-party/qcoro': '@latest'
    'third-party/wayland': '@latest'
    'third-party/wayland-protocols': '@latest'

 - 'on': ['Linux']
   'require':
    'libraries/polkit-qt-1': 'v0.200.0'
    'third-party/packagekit-qt': '@latest'

RuntimeDependencies:
 - 'on': ['Linux']
   'require':
    'network/kio-extras': 'release/25.12'
    'plasma/kactivitymanagerd': '@same'
    'sdk/selenium-webdriver-at-spi': '@same'
 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'
    'plasma/milou': '@same'

Options:
 ctest-arguments: '--repeat until-pass:5'
 use-ccache: True
 require-passing-tests-on: ['@all']
 clang-format-versions: [14, 18]
 run-qmllint: True
