[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/startkde
TryExec=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/startkde
DesktopNames=KDE
Name=Plasma
Name[ca]=Plasma
Name[es]=Plasma
Name[id]=Plasma
Name[nds]=Plasma
Name[nl]=Plasma
Name[pl]=Plazma
Name[pt]=Plasma
Name[pt_BR]=Plasma
Name[sk]=Plasma
Name[sl]=Plasma
Name[sv]=Plasma
Name[uk]=Плазма
Name[x-test]=xxPlasmaxx
Comment=Plasma by KDE
Comment[ca]=Plasma pel KDE
Comment[es]=Plasma, por KDE
Comment[id]=Plasma oleh KDE
Comment[nds]=Plasma vun KDE
Comment[nl]=Plasma door KDE
Comment[pl]=Plazma dzięki KDE
Comment[pt]=Plasma do KDE
Comment[pt_BR]=Plasma do KDE
Comment[sk]=Plasma od KDE
Comment[sl]=KDE Plasma
Comment[sv]=Plasma av KDE
Comment[uk]=Плазма KDE
Comment[x-test]=xxPlasma by KDExx
