[Desktop Entry]
Exec=dbus-run-session @CMAKE_INSTALL_FULL_LIBEXECDIR@/startplasma-dev.sh -wayland
DesktopNames=KDE
Name=Plasma (Development ${CMAKE_INSTALL_FULL_BINDIR})
Name[ca]=Plasma (Desenvolupament ${CMAKE_INSTALL_FULL_BINDIR})
Name[de]=Plasma (Development ${CMAKE_INSTALL_FULL_BINDIR})
Name[en_GB]=Plasma (Development ${CMAKE_INSTALL_FULL_BINDIR})
Name[es]=Plasma (Desarrollo ${CMAKE_INSTALL_FULL_BINDIR})
Name[eu]=Plasma (Garapena ${CMAKE_INSTALL_FULL_BINDIR})
Name[fi]=Plasma (kehitys ${CMAKE_INSTALL_FULL_BINDIR})
Name[fr]=Plasma (Développement ${CMAKE_INSTALL_FULL_BINDIR})
Name[id]=Plasma (Pengembangan${CMAKE_INSTALL_FULL_BINDIR})
Name[it]=Plasma (Sviluppo ${CMAKE_INSTALL_FULL_BINDIR})
Name[lt]=Plasma (Plėtojimas ${CMAKE_INSTALL_FULL_BINDIR})
Name[nl]=Plasma (Ontwikkeling ${CMAKE_INSTALL_FULL_BINDIR})
Name[nn]=Plasma (utvikling ${CMAKE_INSTALL_FULL_BINDIR})
Name[pl]=Plazma (Rozwój ${CMAKE_INSTALL_FULL_BINDIR})
Name[pt]=Plasma (Desenvolvimento ${CMAKE_INSTALL_FULL_BINDIR})
Name[pt_BR]=Plasma (Desenvolvimento ${CMAKE_INSTALL_FULL_BINDIR})
Name[ru]=Plasma (разрабатываемая версия ${CMAKE_INSTALL_FULL_BINDIR})
Name[sk]=Plasma (Development ${CMAKE_INSTALL_FULL_BINDIR})
Name[sv]=Plasma (utveckling ${CMAKE_INSTALL_FULL_BINDIR})
Name[uk]=Пзазма (Розробка ${CMAKE_INSTALL_FULL_BINDIR})
Name[x-test]=xxPlasma (Development ${CMAKE_INSTALL_FULL_BINDIR})xx
Name[zh_CN]=Plasma (开发 ${CMAKE_INSTALL_FULL_BINDIR})
Name[zh_TW]=Plasma（開發版本 ${CMAKE_INSTALL_FULL_BINDIR}）
Comment=Plasma by KDE
Comment[ar]=بلازما كدي
Comment[bs]=Plazma od strane KDe
Comment[ca]=Plasma, creat per la comunitat KDE
Comment[ca@valencia]=Plasma, creat per la comunitat KDE
Comment[cs]=Plasma z KDE
Comment[da]=Plasma fra KDE
Comment[de]=Plasma von KDE
Comment[el]=Plasma από το KDE
Comment[en_GB]=Plasma by KDE
Comment[es]=Plasma, por KDE
Comment[et]=KDE Plasma
Comment[eu]=KDEren Plasma
Comment[fi]=Plasma KDE:ltä
Comment[fr]=Plasma, par KDE
Comment[gl]=Plasma, fornecido por KDE.
Comment[he]=פלזמה באמצעות KDE
Comment[hu]=Plasma a KDE-től
Comment[id]=Plasma oleh KDE
Comment[is]=Plasma frá KDE
Comment[it]=Plasma di KDE
Comment[ja]=Plasma by KDE
Comment[ko]=KDE Plasma
Comment[lt]=Plasmą pagal KDE
Comment[nb]=Plasma av KDE
Comment[nds]=Plasma vun KDE
Comment[nl]=Plasma door KDE
Comment[nn]=Plasma frå KDE
Comment[pa]=KDE ਵਲੋਂ ਪਲਾਜ਼ਮਾ
Comment[pl]=Plazma dzięki KDE
Comment[pt]=Plasma do KDE
Comment[pt_BR]=Plasma do KDE
Comment[ru]=KDE Plasma
Comment[sk]=Plasma od KDE
Comment[sl]=KDE Plasma
Comment[sr]=Плазма од КДЕ‑а
Comment[sr@ijekavian]=Плазма од КДЕ‑а
Comment[sr@ijekavianlatin]=Plasma od KDE‑a
Comment[sr@latin]=Plasma od KDE‑a
Comment[sv]=Plasma av KDE
Comment[tr]=KDE Plasma
Comment[uk]=Плазма KDE
Comment[x-test]=xxPlasma by KDExx
Comment[zh_CN]=KDE Plasma
Comment[zh_TW]=Plasma by KDE
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
